$axure.loadCurrentPage({
  "url":"我的及菜单调整.html",
  "generationDate":new Date(1450243501355.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2211cc08146f41bda02c0d0c0fbc8016",
    "type":"Axure:Page",
    "name":"我的及菜单调整",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9e20c3f7cd324734bcc69f659f53f4cc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "location":{
              "x":400,
              "y":0},
            "size":{
              "width":320,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c14700cd5a04e04ac5dd01d29c81c9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":320,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的及菜单调整/u0.png"}},
{
          "id":"90a62b1e627f477980c7d5052c9630c4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "location":{
              "x":400,
              "y":64},
            "size":{
              "width":320,
              "height":415}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98eecf0eb51a4948bd8b5befd6705d5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "location":{
                  "x":400,
                  "y":64},
                "size":{
                  "width":320,
                  "height":415}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的及菜单调整/u2.png"}},
{
          "id":"cef55b8fa88f4e76b11d065b8caf5f70",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":0,
              "y":180},
            "size":{
              "width":319,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a788799c56c14f40a594a466b78e2b9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":180},
                "size":{
                  "width":319,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的及菜单调整/u4.png"}},
{
          "id":"f9f36ff744954860b77e3163321e1e94",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"27px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":180,
              "y":187},
            "size":{
              "width":129,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0697caf764864a018968b4f02e836750",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"27px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":187},
                "size":{
                  "width":129,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6404414130664b2eb02a5a2f4eb8dd47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":0,
              "y":220},
            "size":{
              "width":319,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"754a930f8a2f461b8b8a3a2dc8693282",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":220},
                "size":{
                  "width":319,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的及菜单调整/u4.png"}},
{
          "id":"42626b7b27c445669f4a416fd4c50527",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":180,
              "y":227},
            "size":{
              "width":129,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f1e56eda73b489b840a0e469228985d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":227},
                "size":{
                  "width":129,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77051db66748472ba55f0915311313de",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":70},
            "size":{
              "width":320,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e091b2847c14c40a4fe713b7c9a967d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":70},
                "size":{
                  "width":320,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的及菜单调整/u12.png"}},
{
          "id":"6e9d50ec4f7240208a08b6cd290a8351",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"19px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1B1B1B},
            "size":{
              "width":320,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0146dc9709de4f1ca764e7aebcc5b24d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"19px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1B1B1B},
                "size":{
                  "width":320,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u0.png"}},
{
          "id":"d6e00d1b0d694aa38757c128a6fb032e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":8},
            "size":{
              "width":56,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18cbf8991ff74803a38efe6fddccf082",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":8},
                "size":{
                  "width":56,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u2.png"}},
{
          "id":"1c13bc6776a14d5ca66b971f5b17fb2e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":12},
            "size":{
              "width":40,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d602703ad1143fab7a161c507b61daa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":12},
                "size":{
                  "width":40,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u4.png"}},
{
          "id":"ad961281e67a4108b5fce1c50508674f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":80},
            "size":{
              "width":58,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08ff65b7ba2e45379d6ab11c1c7b0f4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":80},
                "size":{
                  "width":58,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的及菜单调整/u20.png"}},
{
          "id":"0888a3bba7704a1c9527112f0fd6c0bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"21px",
            "fontWeight":"400",
            "location":{
              "x":94,
              "y":95.5},
            "size":{
              "width":186,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4294be368a5d45b18b68150aae98fac2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"21px",
                "fontWeight":"400",
                "location":{
                  "x":94,
                  "y":95.5},
                "size":{
                  "width":186,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a260217084a4ea2ba538f1d7275ef8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":171,
              "y":233},
            "size":{
              "width":118,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6eca8d7d95a41eca895dc05fda4d6c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":171,
                  "y":233},
                "size":{
                  "width":118,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c41495a3c3974fa6a9c9ecf5adf650df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":0,
              "y":290},
            "size":{
              "width":319,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1636a2504ef4bf8bb7b8a3ba01764e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":290},
                "size":{
                  "width":319,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的及菜单调整/u4.png"}},
{
          "id":"6111d881215549ef8b115a1c0064ce67",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"27px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":180,
              "y":297},
            "size":{
              "width":129,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3af69e5e74124511815ed1a3d342da4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"27px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":297},
                "size":{
                  "width":129,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e6df5f6e9ad48a3bcad7f811ad9aef3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "location":{
              "x":489,
              "y":27},
            "size":{
              "width":143,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3df04aac08b14cf0a6b4511958ea30cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "location":{
                  "x":489,
                  "y":27},
                "size":{
                  "width":143,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的及菜单调整/u30.png"}},
{
          "id":"7b9744c5b36e4aba98a012bdaf97f04d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":400.5,
              "y":27},
            "size":{
              "width":320,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f922a9b17df74cd4a7783f33c15d517e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":400.5,
                  "y":27},
                "size":{
                  "width":320,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cb20f6cb4524f4f8bad5a28be6736e8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "location":{
              "x":400,
              "y":430},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0954a027a12e44ed8d317cc97d587102",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "location":{
                  "x":400,
                  "y":430},
                "size":{
                  "width":320,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的及菜单调整/u34.png"}},
{
          "id":"f7651224e820486f8c7463190760b874",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "location":{
              "x":410,
              "y":438},
            "size":{
              "width":30,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a1002bdc78048ad93c750995e6f6b68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "location":{
                  "x":410,
                  "y":438},
                "size":{
                  "width":30,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的及菜单调整/u36.png"}},
{
          "id":"a76b22c97f3644b987c69a8e9a15d44b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Bold', '华文细黑'",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xF2F2F2},
            "location":{
              "x":400,
              "y":430},
            "size":{
              "width":49,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8efb2d022d0349fd93e7463967877e84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Bold', '华文细黑'",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xF2F2F2},
                "location":{
                  "x":400,
                  "y":430},
                "size":{
                  "width":49,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的及菜单调整/u38.png"}},
{
          "id":"ac9e624d7019480c89f1dd70b4b126de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "location":{
              "x":629,
              "y":370},
            "size":{
              "width":90,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0893ae2db7c4f7cbca1c7c8df3902e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "location":{
                  "x":629,
                  "y":370},
                "size":{
                  "width":90,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的及菜单调整/u40.png"}},
{
          "id":"10606da0efc54eefaa3a65f6619c82cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "location":{
              "x":629,
              "y":400},
            "size":{
              "width":90,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a968a5870f04731b39899bb254f9f6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "location":{
                  "x":629,
                  "y":400},
                "size":{
                  "width":90,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的及菜单调整/u40.png"}},
{
          "id":"cfa3f6ea7f834d33b7cd8ac1cbf3e607",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Bold', '华文细黑'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF434343,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xF2F2F2},
            "location":{
              "x":449,
              "y":430},
            "size":{
              "width":90,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36c2cd6758504ba38772f867d6ab2969",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Bold', '华文细黑'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF434343,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xF2F2F2},
                "location":{
                  "x":449,
                  "y":430},
                "size":{
                  "width":90,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的及菜单调整/u44.png"}},
{
          "id":"257e25ebae8d42ac835ef4242744acf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Bold', '华文细黑'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF434343,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xF2F2F2},
            "location":{
              "x":539,
              "y":430},
            "size":{
              "width":90,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f44bbec43d04f7ba65f045d37f3e7b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Bold', '华文细黑'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF434343,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xF2F2F2},
                "location":{
                  "x":539,
                  "y":430},
                "size":{
                  "width":90,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的及菜单调整/u44.png"}},
{
          "id":"69ea65638d72481984ddc460d4c7279c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Bold', '华文细黑'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF434343,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xF2F2F2},
            "location":{
              "x":629,
              "y":430},
            "size":{
              "width":90,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e5b3b718c174d0785856c09ea2f76d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Bold', '华文细黑'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF434343,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xF2F2F2},
                "location":{
                  "x":629,
                  "y":430},
                "size":{
                  "width":90,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的及菜单调整/u44.png"}},
{
          "id":"3fa9db974e8849a994e0d8b2ad0ffb3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "location":{
              "x":539,
              "y":340},
            "size":{
              "width":90,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52a27b215200473b8d80d16f2998fe9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "location":{
                  "x":539,
                  "y":340},
                "size":{
                  "width":90,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的及菜单调整/u40.png"}},
{
          "id":"c3508edf278a4439ae86f2311975d31f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "location":{
              "x":539,
              "y":370},
            "size":{
              "width":90,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"495a60c3d14a4de1b37ac1d68fd644d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "location":{
                  "x":539,
                  "y":370},
                "size":{
                  "width":90,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的及菜单调整/u40.png"}},
{
          "id":"17cc78d37b75468e97f2195d73690778",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "location":{
              "x":629,
              "y":340},
            "size":{
              "width":90,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ca862e70bd8471dbccde9a8d4b0b6a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "location":{
                  "x":629,
                  "y":340},
                "size":{
                  "width":90,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的及菜单调整/u40.png"}},
{
          "id":"496443ac59714d0e9c087f9bbb8a3fbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "location":{
              "x":539,
              "y":400},
            "size":{
              "width":90,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"228c092bb0194cfd9c89c4a6c6bcb572",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "location":{
                  "x":539,
                  "y":400},
                "size":{
                  "width":90,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的及菜单调整/u40.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9e20c3f7cd324734bcc69f659f53f4cc":{
      "scriptId":"u0"},
    "0c14700cd5a04e04ac5dd01d29c81c9e":{
      "scriptId":"u1"},
    "90a62b1e627f477980c7d5052c9630c4":{
      "scriptId":"u2"},
    "98eecf0eb51a4948bd8b5befd6705d5e":{
      "scriptId":"u3"},
    "cef55b8fa88f4e76b11d065b8caf5f70":{
      "scriptId":"u4"},
    "a788799c56c14f40a594a466b78e2b9a":{
      "scriptId":"u5"},
    "f9f36ff744954860b77e3163321e1e94":{
      "scriptId":"u6"},
    "0697caf764864a018968b4f02e836750":{
      "scriptId":"u7"},
    "6404414130664b2eb02a5a2f4eb8dd47":{
      "scriptId":"u8"},
    "754a930f8a2f461b8b8a3a2dc8693282":{
      "scriptId":"u9"},
    "42626b7b27c445669f4a416fd4c50527":{
      "scriptId":"u10"},
    "5f1e56eda73b489b840a0e469228985d":{
      "scriptId":"u11"},
    "77051db66748472ba55f0915311313de":{
      "scriptId":"u12"},
    "3e091b2847c14c40a4fe713b7c9a967d":{
      "scriptId":"u13"},
    "6e9d50ec4f7240208a08b6cd290a8351":{
      "scriptId":"u14"},
    "0146dc9709de4f1ca764e7aebcc5b24d":{
      "scriptId":"u15"},
    "d6e00d1b0d694aa38757c128a6fb032e":{
      "scriptId":"u16"},
    "18cbf8991ff74803a38efe6fddccf082":{
      "scriptId":"u17"},
    "1c13bc6776a14d5ca66b971f5b17fb2e":{
      "scriptId":"u18"},
    "5d602703ad1143fab7a161c507b61daa":{
      "scriptId":"u19"},
    "ad961281e67a4108b5fce1c50508674f":{
      "scriptId":"u20"},
    "08ff65b7ba2e45379d6ab11c1c7b0f4c":{
      "scriptId":"u21"},
    "0888a3bba7704a1c9527112f0fd6c0bf":{
      "scriptId":"u22"},
    "4294be368a5d45b18b68150aae98fac2":{
      "scriptId":"u23"},
    "4a260217084a4ea2ba538f1d7275ef8a":{
      "scriptId":"u24"},
    "a6eca8d7d95a41eca895dc05fda4d6c1":{
      "scriptId":"u25"},
    "c41495a3c3974fa6a9c9ecf5adf650df":{
      "scriptId":"u26"},
    "b1636a2504ef4bf8bb7b8a3ba01764e3":{
      "scriptId":"u27"},
    "6111d881215549ef8b115a1c0064ce67":{
      "scriptId":"u28"},
    "3af69e5e74124511815ed1a3d342da4c":{
      "scriptId":"u29"},
    "5e6df5f6e9ad48a3bcad7f811ad9aef3":{
      "scriptId":"u30"},
    "3df04aac08b14cf0a6b4511958ea30cc":{
      "scriptId":"u31"},
    "7b9744c5b36e4aba98a012bdaf97f04d":{
      "scriptId":"u32"},
    "f922a9b17df74cd4a7783f33c15d517e":{
      "scriptId":"u33"},
    "4cb20f6cb4524f4f8bad5a28be6736e8":{
      "scriptId":"u34"},
    "0954a027a12e44ed8d317cc97d587102":{
      "scriptId":"u35"},
    "f7651224e820486f8c7463190760b874":{
      "scriptId":"u36"},
    "2a1002bdc78048ad93c750995e6f6b68":{
      "scriptId":"u37"},
    "a76b22c97f3644b987c69a8e9a15d44b":{
      "scriptId":"u38"},
    "8efb2d022d0349fd93e7463967877e84":{
      "scriptId":"u39"},
    "ac9e624d7019480c89f1dd70b4b126de":{
      "scriptId":"u40"},
    "e0893ae2db7c4f7cbca1c7c8df3902e0":{
      "scriptId":"u41"},
    "10606da0efc54eefaa3a65f6619c82cc":{
      "scriptId":"u42"},
    "3a968a5870f04731b39899bb254f9f6e":{
      "scriptId":"u43"},
    "cfa3f6ea7f834d33b7cd8ac1cbf3e607":{
      "scriptId":"u44"},
    "36c2cd6758504ba38772f867d6ab2969":{
      "scriptId":"u45"},
    "257e25ebae8d42ac835ef4242744acf1":{
      "scriptId":"u46"},
    "7f44bbec43d04f7ba65f045d37f3e7b8":{
      "scriptId":"u47"},
    "69ea65638d72481984ddc460d4c7279c":{
      "scriptId":"u48"},
    "6e5b3b718c174d0785856c09ea2f76d2":{
      "scriptId":"u49"},
    "3fa9db974e8849a994e0d8b2ad0ffb3d":{
      "scriptId":"u50"},
    "52a27b215200473b8d80d16f2998fe9b":{
      "scriptId":"u51"},
    "c3508edf278a4439ae86f2311975d31f":{
      "scriptId":"u52"},
    "495a60c3d14a4de1b37ac1d68fd644d5":{
      "scriptId":"u53"},
    "17cc78d37b75468e97f2195d73690778":{
      "scriptId":"u54"},
    "3ca862e70bd8471dbccde9a8d4b0b6a0":{
      "scriptId":"u55"},
    "496443ac59714d0e9c087f9bbb8a3fbe":{
      "scriptId":"u56"},
    "228c092bb0194cfd9c89c4a6c6bcb572":{
      "scriptId":"u57"}}});