$axure.loadCurrentPage({
  "url":"购物车提示语调整.html",
  "generationDate":new Date(1450243501497.19),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"93ba39870e7f4ae5b535eb2298969e77",
    "type":"Axure:Page",
    "name":"购物车提示语调整",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e223c41ff74e43ccb866486b04a56584",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":0,
              "y":110},
            "size":{
              "width":320,
              "height":260},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"944f874177514451be4a57dab892d270",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":0,
                  "y":110},
                "size":{
                  "width":320,
                  "height":260},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车提示语调整/u0.png"}},
{
          "id":"8ea432ca5008406eb5b75c8659124623",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":258},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b2849f7f7a04069b6047f9de7cec07c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":258},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车提示语调整/u2.png"}},
{
          "id":"152ba5191b204d3bb4612482f4979fa9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":97,
              "y":258},
            "size":{
              "width":198,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9564d451005a42c7b33032c0ed237008",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":97,
                  "y":258},
                "size":{
                  "width":198,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31933dca5eb4439c90afd178a93e4ef2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":99,
              "y":308},
            "size":{
              "width":105,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c3e84f5944e403a83a1e7105e24c549",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":99,
                  "y":308},
                "size":{
                  "width":105,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df6be7ea77b44cd18942edfd686eec5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":96,
              "y":283},
            "size":{
              "width":96,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f497f515538545b49fc70fe3ec1a7845",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":96,
                  "y":283},
                "size":{
                  "width":96,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f833376b8f14e7ea38d010114176e77",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":142},
            "size":{
              "width":95,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ff165174cfa41838409bec23e405dce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":142},
                "size":{
                  "width":95,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e7e042f4ca644c85b89c63ca1b06fad3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":130},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e4b09b54bac498083ec4dccf735cdb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":130},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车提示语调整/u2.png"}},
{
          "id":"49edb70f34084cd39bd9c9ca10b66542",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":98,
              "y":130},
            "size":{
              "width":204,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eba04393a2a7413581d8b80af43556d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":98,
                  "y":130},
                "size":{
                  "width":204,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e63586a75f74a6eb8b7b78440dbd6e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":99,
              "y":175},
            "size":{
              "width":203,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fc7efa25f5547ddb5ed3abc9eb7c520",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":99,
                  "y":175},
                "size":{
                  "width":203,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"323c283cf0794fd2b34f191697b4292a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":98,
              "y":150},
            "size":{
              "width":88,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32608f5b1158495fb8b37db5bde3f992",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":98,
                  "y":150},
                "size":{
                  "width":88,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"724bf8d7310348788922ac23fade0fd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "location":{
              "x":154,
              "y":210},
            "size":{
              "width":20,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc34286fa30a473c9bea4c5e0c2332dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "location":{
                  "x":154,
                  "y":210},
                "size":{
                  "width":20,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车提示语调整/u20.png"}},
{
          "id":"b96c256dd542492cb1fdeabb35e51f25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "location":{
              "x":99,
              "y":210},
            "size":{
              "width":20,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d11e5a5337b485aac3934af6b70a607",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "location":{
                  "x":99,
                  "y":210},
                "size":{
                  "width":20,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车提示语调整/u20.png"}},
{
          "id":"400ff6480cb1432d898dd124ad20e74b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":119,
              "y":210},
            "size":{
              "width":35,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88a767940a0349a7a603fbe594d056a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":119,
                  "y":210},
                "size":{
                  "width":35,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车提示语调整/u24.png"}},
{
          "id":"2637237d87ee4f0aa107d3c1f8c162b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "location":{
              "x":154,
              "y":333},
            "size":{
              "width":20,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbb83081082a49d5a2d11c7550525629",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "location":{
                  "x":154,
                  "y":333},
                "size":{
                  "width":20,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车提示语调整/u20.png"}},
{
          "id":"398d3b7ef63b451b991b5169f0f39d4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":99,
              "y":333},
            "size":{
              "width":20,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59f7922a809340f2ac77f0b6669fc1c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":99,
                  "y":333},
                "size":{
                  "width":20,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车提示语调整/u28.png"}},
{
          "id":"02137a058eb049f29aa1a0783d914cc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":119,
              "y":333},
            "size":{
              "width":35,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb26a1f505f84eb4b89adf77b8e3e7e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":119,
                  "y":333},
                "size":{
                  "width":35,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车提示语调整/u24.png"}},
{
          "id":"589500e651644f75a9239910a50b1767",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":0,
              "y":70},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49fd761b1c3c4a8f928d4edd39d3940c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":0,
                  "y":70},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车提示语调整/u32.png"}},
{
          "id":"9382f695ba104dbc9474f318fe1e2e7c",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":18,
              "y":82},
            "size":{
              "width":221,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"123962b9707a4e7297359559857c4066",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":18,
                  "y":82},
                "size":{
                  "width":221,
                  "height":17}},
              "adaptiveStyles":{
}}]},
{
          "id":"e10a1b02ac5e4d53aeb63c882de24f62",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":240},
            "size":{
              "width":306,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/购物车提示语调整/u36_line.png"}},
{
          "id":"de7d8ed41f7f45929e1fb3d597c29c8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE1ECEE},
            "location":{
              "x":270,
              "y":78},
            "size":{
              "width":40,
              "height":25},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95a2889c83384cefa1d12c503760a0df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE1ECEE},
                "location":{
                  "x":270,
                  "y":78},
                "size":{
                  "width":40,
                  "height":25},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车提示语调整/u37.png"}},
{
          "id":"fd9561c317814a99b7a1f2c5b2479d00",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"right",
            "location":{
              "x":0,
              "y":370},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"494e7e8c7bf24895a6615378317df047",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"right",
                "location":{
                  "x":0,
                  "y":370},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车提示语调整/u32.png"}},
{
          "id":"6829aafee80c468ea4e35c5c8de5abe9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"19px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1B1B1B},
            "size":{
              "width":320,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2909f10f101a45eda8d9f86154063892",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"19px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1B1B1B},
                "size":{
                  "width":320,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u0.png"}},
{
          "id":"409b87e3f6584414bb396aeb98234c8b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":9},
            "size":{
              "width":56,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfd1b63928e240e7a845f8e76a42d25f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":9},
                "size":{
                  "width":56,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u2.png"}},
{
          "id":"7f0c4848f5fd4156b93108c53ce986fd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":12},
            "size":{
              "width":40,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ce3c85b9b094531ad2f2bfcbac29df6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":12},
                "size":{
                  "width":40,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u4.png"}},
{
          "id":"d788895b8ec245a9a8cfb749a471dd03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":48,
              "y":382},
            "size":{
              "width":163,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f011af76b7f45579152bbbb0a1e9775",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":48,
                  "y":382},
                "size":{
                  "width":163,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1c22dd4bb2c4f3cb6f6be877b297c02",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":270},
            "size":{
              "width":95,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbce0e189f274aebbef9a3ef509d7461",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":270},
                "size":{
                  "width":95,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"088c084dedae439588b6ca271ee13714",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFC7EDCC},
            "location":{
              "x":340,
              "y":70},
            "size":{
              "width":320,
              "height":340}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09515c8c6ea04185bb3b05fc4be0ea74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC7EDCC},
                "location":{
                  "x":340,
                  "y":70},
                "size":{
                  "width":320,
                  "height":340}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车提示语调整/u51.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e223c41ff74e43ccb866486b04a56584":{
      "scriptId":"u0"},
    "944f874177514451be4a57dab892d270":{
      "scriptId":"u1"},
    "8ea432ca5008406eb5b75c8659124623":{
      "scriptId":"u2"},
    "9b2849f7f7a04069b6047f9de7cec07c":{
      "scriptId":"u3"},
    "152ba5191b204d3bb4612482f4979fa9":{
      "scriptId":"u4"},
    "9564d451005a42c7b33032c0ed237008":{
      "scriptId":"u5"},
    "31933dca5eb4439c90afd178a93e4ef2":{
      "scriptId":"u6"},
    "3c3e84f5944e403a83a1e7105e24c549":{
      "scriptId":"u7"},
    "df6be7ea77b44cd18942edfd686eec5e":{
      "scriptId":"u8"},
    "f497f515538545b49fc70fe3ec1a7845":{
      "scriptId":"u9"},
    "7f833376b8f14e7ea38d010114176e77":{
      "scriptId":"u10"},
    "8ff165174cfa41838409bec23e405dce":{
      "scriptId":"u11"},
    "e7e042f4ca644c85b89c63ca1b06fad3":{
      "scriptId":"u12"},
    "5e4b09b54bac498083ec4dccf735cdb3":{
      "scriptId":"u13"},
    "49edb70f34084cd39bd9c9ca10b66542":{
      "scriptId":"u14"},
    "eba04393a2a7413581d8b80af43556d6":{
      "scriptId":"u15"},
    "3e63586a75f74a6eb8b7b78440dbd6e1":{
      "scriptId":"u16"},
    "8fc7efa25f5547ddb5ed3abc9eb7c520":{
      "scriptId":"u17"},
    "323c283cf0794fd2b34f191697b4292a":{
      "scriptId":"u18"},
    "32608f5b1158495fb8b37db5bde3f992":{
      "scriptId":"u19"},
    "724bf8d7310348788922ac23fade0fd4":{
      "scriptId":"u20"},
    "fc34286fa30a473c9bea4c5e0c2332dd":{
      "scriptId":"u21"},
    "b96c256dd542492cb1fdeabb35e51f25":{
      "scriptId":"u22"},
    "7d11e5a5337b485aac3934af6b70a607":{
      "scriptId":"u23"},
    "400ff6480cb1432d898dd124ad20e74b":{
      "scriptId":"u24"},
    "88a767940a0349a7a603fbe594d056a5":{
      "scriptId":"u25"},
    "2637237d87ee4f0aa107d3c1f8c162b0":{
      "scriptId":"u26"},
    "bbb83081082a49d5a2d11c7550525629":{
      "scriptId":"u27"},
    "398d3b7ef63b451b991b5169f0f39d4f":{
      "scriptId":"u28"},
    "59f7922a809340f2ac77f0b6669fc1c6":{
      "scriptId":"u29"},
    "02137a058eb049f29aa1a0783d914cc4":{
      "scriptId":"u30"},
    "eb26a1f505f84eb4b89adf77b8e3e7e3":{
      "scriptId":"u31"},
    "589500e651644f75a9239910a50b1767":{
      "scriptId":"u32"},
    "49fd761b1c3c4a8f928d4edd39d3940c":{
      "scriptId":"u33"},
    "9382f695ba104dbc9474f318fe1e2e7c":{
      "scriptId":"u34"},
    "123962b9707a4e7297359559857c4066":{
      "scriptId":"u35"},
    "e10a1b02ac5e4d53aeb63c882de24f62":{
      "scriptId":"u36"},
    "de7d8ed41f7f45929e1fb3d597c29c8d":{
      "scriptId":"u37"},
    "95a2889c83384cefa1d12c503760a0df":{
      "scriptId":"u38"},
    "fd9561c317814a99b7a1f2c5b2479d00":{
      "scriptId":"u39"},
    "494e7e8c7bf24895a6615378317df047":{
      "scriptId":"u40"},
    "6829aafee80c468ea4e35c5c8de5abe9":{
      "scriptId":"u41"},
    "2909f10f101a45eda8d9f86154063892":{
      "scriptId":"u42"},
    "409b87e3f6584414bb396aeb98234c8b":{
      "scriptId":"u43"},
    "bfd1b63928e240e7a845f8e76a42d25f":{
      "scriptId":"u44"},
    "7f0c4848f5fd4156b93108c53ce986fd":{
      "scriptId":"u45"},
    "3ce3c85b9b094531ad2f2bfcbac29df6":{
      "scriptId":"u46"},
    "d788895b8ec245a9a8cfb749a471dd03":{
      "scriptId":"u47"},
    "6f011af76b7f45579152bbbb0a1e9775":{
      "scriptId":"u48"},
    "e1c22dd4bb2c4f3cb6f6be877b297c02":{
      "scriptId":"u49"},
    "cbce0e189f274aebbef9a3ef509d7461":{
      "scriptId":"u50"},
    "088c084dedae439588b6ca271ee13714":{
      "scriptId":"u51"},
    "09515c8c6ea04185bb3b05fc4be0ea74":{
      "scriptId":"u52"}}});