$axure.loadCurrentPage({
  "url":"后台订单管理.html",
  "generationDate":new Date(1450243501825.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0a708f6a96c74ebab8838641a4515308",
    "type":"Axure:Page",
    "name":"后台订单管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f47382fd203140b2b3b21f150edfb60a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1289,
              "height":337}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7590aceb58694aac85c17ca390e5bfce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1289,
                  "height":337}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台订单管理/u0.png"}},
{
          "id":"e9febceba7364b84aa73824aeff5e8ee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":336},
            "size":{
              "width":1287,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c777bb5c44ac493187ab25aaf30f845d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":336},
                "size":{
                  "width":1287,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台订单管理/u2.png"}},
{
          "id":"18b8ed140b334444827c58d1d79d735e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":970,
              "y":404},
            "size":{
              "width":120,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c533ca6ac25140c8bbe81da63f7636d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":970,
                  "y":404},
                "size":{
                  "width":120,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台订单管理/u4.png"}},
{
          "id":"733cea97f7734401971992a96aa34d73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":970,
              "y":467},
            "size":{
              "width":120,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98b617402eac47ae99b2d42e5c3682c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":970,
                  "y":467},
                "size":{
                  "width":120,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台订单管理/u6.png"}},
{
          "id":"99e5956d0c1147e7ae2bb1f690bfa1f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFC7EDCC},
            "location":{
              "x":240,
              "y":410},
            "size":{
              "width":320,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30dd885b7df047dd806c872fef1e018c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC7EDCC},
                "location":{
                  "x":240,
                  "y":410},
                "size":{
                  "width":320,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台订单管理/u8.png"}},
{
          "id":"22a400ed03a647848937392e856871e5",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1040,
              "y":170},
            "size":{
              "width":10,
              "height":234},
            "borderWidth":"5"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/后台订单管理/u10_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/后台订单管理/u10_line.png"}},
{
          "id":"08e124a959f346e1860da87c911006a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1100,
              "y":404},
            "size":{
              "width":120,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0275e5180263487f893d022c2cf665d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1100,
                  "y":404},
                "size":{
                  "width":120,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台订单管理/u4.png"}},
{
          "id":"df52d524fda24421b5472af75abd4040",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1100,
              "y":467},
            "size":{
              "width":120,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"078436588dbb416982707612ef758237",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1100,
                  "y":467},
                "size":{
                  "width":120,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台订单管理/u6.png"}},
{
          "id":"f6e74eba547346408df89119e9181a21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1230,
              "y":404},
            "size":{
              "width":120,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97690b1bf6474d3eaae0cf74d0f90b9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1230,
                  "y":404},
                "size":{
                  "width":120,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台订单管理/u4.png"}},
{
          "id":"296590305eee456197c34b91edb8660c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1230,
              "y":467},
            "size":{
              "width":120,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0c300bbec0c4cdbbc98e4beb1938b55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1230,
                  "y":467},
                "size":{
                  "width":120,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台订单管理/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f47382fd203140b2b3b21f150edfb60a":{
      "scriptId":"u0"},
    "7590aceb58694aac85c17ca390e5bfce":{
      "scriptId":"u1"},
    "e9febceba7364b84aa73824aeff5e8ee":{
      "scriptId":"u2"},
    "c777bb5c44ac493187ab25aaf30f845d":{
      "scriptId":"u3"},
    "18b8ed140b334444827c58d1d79d735e":{
      "scriptId":"u4"},
    "c533ca6ac25140c8bbe81da63f7636d7":{
      "scriptId":"u5"},
    "733cea97f7734401971992a96aa34d73":{
      "scriptId":"u6"},
    "98b617402eac47ae99b2d42e5c3682c3":{
      "scriptId":"u7"},
    "99e5956d0c1147e7ae2bb1f690bfa1f0":{
      "scriptId":"u8"},
    "30dd885b7df047dd806c872fef1e018c":{
      "scriptId":"u9"},
    "22a400ed03a647848937392e856871e5":{
      "scriptId":"u10"},
    "08e124a959f346e1860da87c911006a5":{
      "scriptId":"u11"},
    "0275e5180263487f893d022c2cf665d8":{
      "scriptId":"u12"},
    "df52d524fda24421b5472af75abd4040":{
      "scriptId":"u13"},
    "078436588dbb416982707612ef758237":{
      "scriptId":"u14"},
    "f6e74eba547346408df89119e9181a21":{
      "scriptId":"u15"},
    "97690b1bf6474d3eaae0cf74d0f90b9f":{
      "scriptId":"u16"},
    "296590305eee456197c34b91edb8660c":{
      "scriptId":"u17"},
    "e0c300bbec0c4cdbbc98e4beb1938b55":{
      "scriptId":"u18"}}});