$axure.loadCurrentPage({
  "url":"添加商品新增商家优惠码的提示.html",
  "generationDate":new Date(1450243501761.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a1e713df653941bf8a9c809819f18c1b",
    "type":"Axure:Page",
    "name":"添加商品新增商家优惠码的提示",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e2708037250f4352a21f191fc3da5e7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"19px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1B1B1B},
            "size":{
              "width":320,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1cc7b1c81214e50b262556319289554",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"19px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1B1B1B},
                "size":{
                  "width":320,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u0.png"}},
{
          "id":"617f75037ac2488ba378297e423a9d55",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":9},
            "size":{
              "width":56,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be058f42e5734315a7f19e04712fb982",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":9},
                "size":{
                  "width":56,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u2.png"}},
{
          "id":"f240c7b8a4584ff4ad5637d7c7af153c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":12},
            "size":{
              "width":40,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f3bc84fdafb4c3bb1f41665f06e25cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":12},
                "size":{
                  "width":40,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u4.png"}},
{
          "id":"4e0d2c7c439742f7be6fef5f8be3d2a3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":70},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3942554e7e464ae2a3dcd002a29c2c3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":70},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加商品新增商家优惠码的提示/u6.png"}},
{
          "id":"aaab45cf410e474b93af46594aa97af3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":70},
            "size":{
              "width":230,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af5f0ef93db145758998c0be55f3510b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":70},
                "size":{
                  "width":230,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8820ae38fb64335a884dfc91d815c6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":110},
            "size":{
              "width":219,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91c06b67d0124c5187387410319d4489",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":110},
                "size":{
                  "width":219,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d58b3742d5c478698a69a176413c0a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":80,
              "y":130},
            "size":{
              "width":219,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c5203372c7245b3bb8a777bda56601a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":130},
                "size":{
                  "width":219,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48317e645cd447bbae08ab1bfe11a36e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":170},
            "size":{
              "width":219,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16cacdffed774146862672a7f739db17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":170},
                "size":{
                  "width":219,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43f616ca55224072af3c09fb83719942",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":13,
              "y":300},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73c5042822de492cbebfed505808c260",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":13,
                  "y":300},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11f54b7581094700a2aa6bb4b3da0ce5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":300},
            "size":{
              "width":50,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9b19110dfb94ef7a39445e6bf5c1401",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":300},
                "size":{
                  "width":50,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加商品新增商家优惠码的提示/u18.png"}},
{
          "id":"b314d4967d0348eca47a17234293c6d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":300},
            "size":{
              "width":50,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35d4a0f15d16441986c68c1634e92c7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":300},
                "size":{
                  "width":50,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加商品新增商家优惠码的提示/u18.png"}},
{
          "id":"7ceb178cfbc34348897482e213cb367c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":300},
            "size":{
              "width":50,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2038a1018eb54d86bb4f9ed03bcab5a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":300},
                "size":{
                  "width":50,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加商品新增商家优惠码的提示/u18.png"}},
{
          "id":"1c28a9c814a54e31bae5aafc2bc3873c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":13,
              "y":326},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"587a53d9c2684ebd9461f443f7a9d8ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":13,
                  "y":326},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b62d92409e714cdf86bcf8248010b6c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":326},
            "size":{
              "width":50,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cf4943ab3d94a3b9644171a94203769",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":326},
                "size":{
                  "width":50,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加商品新增商家优惠码的提示/u18.png"}},
{
          "id":"affdaf958eaa49bfab8d3a3bed6bab50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":326},
            "size":{
              "width":50,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"815752d2b8004066976e96db4942c7e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":326},
                "size":{
                  "width":50,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加商品新增商家优惠码的提示/u18.png"}},
{
          "id":"1475cd7d3b984c23ab5ae980fb7a0404",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":326},
            "size":{
              "width":50,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a74afdc9eb34454e8026050c743eeac2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":326},
                "size":{
                  "width":50,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加商品新增商家优惠码的提示/u18.png"}},
{
          "id":"eacd5ea3f3ff458fbf8d1d1b6cb61ce6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":13,
              "y":353},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f150c2de39b4ac0be4ce45ef7cf6eef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":13,
                  "y":353},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2027afd89a7437299014276552b5ae2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":353},
            "size":{
              "width":50,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dc2e2f7319645639456e5b6c2e6a8e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":353},
                "size":{
                  "width":50,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加商品新增商家优惠码的提示/u18.png"}},
{
          "id":"8c9a3d13149f4de88ac34cbd9f478c7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":100,
              "y":353},
            "size":{
              "width":20,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d58dbe4562024f31ad4fef15ab0d0668",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":100,
                  "y":353},
                "size":{
                  "width":20,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加商品新增商家优惠码的提示/u36.png"}},
{
          "id":"09525e54f5a4447bb26dff750dea4250",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":353},
            "size":{
              "width":20,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c65fe6214344c94a2702021eacc657c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":353},
                "size":{
                  "width":20,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加商品新增商家优惠码的提示/u38.png"}},
{
          "id":"b3198427930a406c9b8c247870804e56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":240},
            "size":{
              "width":220,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dee0fa4c40b44fcc8224ee0f1a65e324",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":240},
                "size":{
                  "width":220,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41296f06f563436cae0cded8f4388ad0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":270},
            "size":{
              "width":220,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7900f0fed6884a4fb5a397d04ba96343",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":270},
                "size":{
                  "width":220,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f232d41bdfb4a8cbb3566d21af649af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":13,
              "y":240},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6585d1b62d83482f969d4dc00ee54602",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":13,
                  "y":240},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51194362629e4c199afdfbb9ce4006f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":13,
              "y":270},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08fdc9eb6f3743cd9e0120cb0baa6b5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":13,
                  "y":270},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"672be948eb71472b82cb6e31d6c1383e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":220},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/添加商品新增商家优惠码的提示/u48_line.png"}},
{
          "id":"2f44a02d4c58492789fa182c30a487dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":0,
              "y":600},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"688b1f2cf8584311b7e05a65bb5e83fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":0,
                  "y":600},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加商品新增商家优惠码的提示/u49.png"}},
{
          "id":"51dc9914185b46f6859fd6b30bc987ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":16,
              "y":610},
            "size":{
              "width":290,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bb1349875a84648ab3c801d6868a53d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":16,
                  "y":610},
                "size":{
                  "width":290,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u38.png"}},
{
          "id":"2abee559ea1843ab8ed1623233c82989",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":400},
            "size":{
              "width":117,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bba17919117c4d07a90ba614e867f0c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":400},
                "size":{
                  "width":117,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed56b4e99361417888f2e407222630e7",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":236,
              "y":441},
            "size":{
              "width":70,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7eb80ca3ca5e460fbdaf299f0af98e38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":236,
                  "y":441},
                "size":{
                  "width":70,
                  "height":15}},
              "adaptiveStyles":{
}}]},
{
          "id":"55714b75f8cd4beea5f40ccd0f2dfb87",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":156,
              "y":441},
            "size":{
              "width":70,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e55e6c52c0945168953f57b952c9e2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":156,
                  "y":441},
                "size":{
                  "width":70,
                  "height":15}},
              "adaptiveStyles":{
}}]},
{
          "id":"56419757ebf24b129e519c6fd6888626",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":516},
            "size":{
              "width":296,
              "height":34}},
          "adaptiveStyles":{
}},
{
          "id":"741561f6e31b4c50bb8c36c60f87f355",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":490},
            "size":{
              "width":117,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71809ca72bcb432b826acb90bbe91655",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":490},
                "size":{
                  "width":117,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"001fcbac12e84c96b2e2f679c95c084b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":10,
              "y":441},
            "size":{
              "width":146,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e40455f471474151a270fd6d45277d03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":10,
                  "y":441},
                "size":{
                  "width":146,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"053c0985af6641b7a7e61555d07daf8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":416},
            "size":{
              "width":290,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91f7451838ad4804a9bdb036a0bc81c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":416},
                "size":{
                  "width":290,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fad51dc494548fa9c3c26f486c82568",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":220,
              "y":400},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"9e7e6af6e794438c9386f74f04240099",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFC7EDCC},
            "location":{
              "x":350,
              "y":400},
            "size":{
              "width":550,
              "height":260}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e41ca151371d49eb98ff743e3bd5eba4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC7EDCC},
                "location":{
                  "x":350,
                  "y":400},
                "size":{
                  "width":550,
                  "height":260}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加商品新增商家优惠码的提示/u67.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e2708037250f4352a21f191fc3da5e7f":{
      "scriptId":"u0"},
    "e1cc7b1c81214e50b262556319289554":{
      "scriptId":"u1"},
    "617f75037ac2488ba378297e423a9d55":{
      "scriptId":"u2"},
    "be058f42e5734315a7f19e04712fb982":{
      "scriptId":"u3"},
    "f240c7b8a4584ff4ad5637d7c7af153c":{
      "scriptId":"u4"},
    "7f3bc84fdafb4c3bb1f41665f06e25cd":{
      "scriptId":"u5"},
    "4e0d2c7c439742f7be6fef5f8be3d2a3":{
      "scriptId":"u6"},
    "3942554e7e464ae2a3dcd002a29c2c3a":{
      "scriptId":"u7"},
    "aaab45cf410e474b93af46594aa97af3":{
      "scriptId":"u8"},
    "af5f0ef93db145758998c0be55f3510b":{
      "scriptId":"u9"},
    "b8820ae38fb64335a884dfc91d815c6d":{
      "scriptId":"u10"},
    "91c06b67d0124c5187387410319d4489":{
      "scriptId":"u11"},
    "9d58b3742d5c478698a69a176413c0a2":{
      "scriptId":"u12"},
    "8c5203372c7245b3bb8a777bda56601a":{
      "scriptId":"u13"},
    "48317e645cd447bbae08ab1bfe11a36e":{
      "scriptId":"u14"},
    "16cacdffed774146862672a7f739db17":{
      "scriptId":"u15"},
    "43f616ca55224072af3c09fb83719942":{
      "scriptId":"u16"},
    "73c5042822de492cbebfed505808c260":{
      "scriptId":"u17"},
    "11f54b7581094700a2aa6bb4b3da0ce5":{
      "scriptId":"u18"},
    "b9b19110dfb94ef7a39445e6bf5c1401":{
      "scriptId":"u19"},
    "b314d4967d0348eca47a17234293c6d3":{
      "scriptId":"u20"},
    "35d4a0f15d16441986c68c1634e92c7d":{
      "scriptId":"u21"},
    "7ceb178cfbc34348897482e213cb367c":{
      "scriptId":"u22"},
    "2038a1018eb54d86bb4f9ed03bcab5a4":{
      "scriptId":"u23"},
    "1c28a9c814a54e31bae5aafc2bc3873c":{
      "scriptId":"u24"},
    "587a53d9c2684ebd9461f443f7a9d8ac":{
      "scriptId":"u25"},
    "b62d92409e714cdf86bcf8248010b6c8":{
      "scriptId":"u26"},
    "0cf4943ab3d94a3b9644171a94203769":{
      "scriptId":"u27"},
    "affdaf958eaa49bfab8d3a3bed6bab50":{
      "scriptId":"u28"},
    "815752d2b8004066976e96db4942c7e3":{
      "scriptId":"u29"},
    "1475cd7d3b984c23ab5ae980fb7a0404":{
      "scriptId":"u30"},
    "a74afdc9eb34454e8026050c743eeac2":{
      "scriptId":"u31"},
    "eacd5ea3f3ff458fbf8d1d1b6cb61ce6":{
      "scriptId":"u32"},
    "2f150c2de39b4ac0be4ce45ef7cf6eef":{
      "scriptId":"u33"},
    "f2027afd89a7437299014276552b5ae2":{
      "scriptId":"u34"},
    "9dc2e2f7319645639456e5b6c2e6a8e0":{
      "scriptId":"u35"},
    "8c9a3d13149f4de88ac34cbd9f478c7c":{
      "scriptId":"u36"},
    "d58dbe4562024f31ad4fef15ab0d0668":{
      "scriptId":"u37"},
    "09525e54f5a4447bb26dff750dea4250":{
      "scriptId":"u38"},
    "6c65fe6214344c94a2702021eacc657c":{
      "scriptId":"u39"},
    "b3198427930a406c9b8c247870804e56":{
      "scriptId":"u40"},
    "dee0fa4c40b44fcc8224ee0f1a65e324":{
      "scriptId":"u41"},
    "41296f06f563436cae0cded8f4388ad0":{
      "scriptId":"u42"},
    "7900f0fed6884a4fb5a397d04ba96343":{
      "scriptId":"u43"},
    "4f232d41bdfb4a8cbb3566d21af649af":{
      "scriptId":"u44"},
    "6585d1b62d83482f969d4dc00ee54602":{
      "scriptId":"u45"},
    "51194362629e4c199afdfbb9ce4006f9":{
      "scriptId":"u46"},
    "08fdc9eb6f3743cd9e0120cb0baa6b5c":{
      "scriptId":"u47"},
    "672be948eb71472b82cb6e31d6c1383e":{
      "scriptId":"u48"},
    "2f44a02d4c58492789fa182c30a487dc":{
      "scriptId":"u49"},
    "688b1f2cf8584311b7e05a65bb5e83fa":{
      "scriptId":"u50"},
    "51dc9914185b46f6859fd6b30bc987ee":{
      "scriptId":"u51"},
    "0bb1349875a84648ab3c801d6868a53d":{
      "scriptId":"u52"},
    "2abee559ea1843ab8ed1623233c82989":{
      "scriptId":"u53"},
    "bba17919117c4d07a90ba614e867f0c0":{
      "scriptId":"u54"},
    "ed56b4e99361417888f2e407222630e7":{
      "scriptId":"u55"},
    "7eb80ca3ca5e460fbdaf299f0af98e38":{
      "scriptId":"u56"},
    "55714b75f8cd4beea5f40ccd0f2dfb87":{
      "scriptId":"u57"},
    "7e55e6c52c0945168953f57b952c9e2f":{
      "scriptId":"u58"},
    "56419757ebf24b129e519c6fd6888626":{
      "scriptId":"u59"},
    "741561f6e31b4c50bb8c36c60f87f355":{
      "scriptId":"u60"},
    "71809ca72bcb432b826acb90bbe91655":{
      "scriptId":"u61"},
    "001fcbac12e84c96b2e2f679c95c084b":{
      "scriptId":"u62"},
    "e40455f471474151a270fd6d45277d03":{
      "scriptId":"u63"},
    "053c0985af6641b7a7e61555d07daf8a":{
      "scriptId":"u64"},
    "91f7451838ad4804a9bdb036a0bc81c9":{
      "scriptId":"u65"},
    "7fad51dc494548fa9c3c26f486c82568":{
      "scriptId":"u66"},
    "9e7e6af6e794438c9386f74f04240099":{
      "scriptId":"u67"},
    "e41ca151371d49eb98ff743e3bd5eba4":{
      "scriptId":"u68"}}});